services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: blood-donation-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: blooddonation
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - blood-donation-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/blooddonation --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blood-donation-backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blooddonation
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-2024
      - PORT=5000
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - blood-donation-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database Seeder (runs once and exits)
  seeder:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blood-donation-seeder
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blooddonation
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - blood-donation-network
    command: ["node", "scripts/seed-docker-data.js"]
    restart: "no"

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5000
    container_name: blood-donation-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
      seeder:
        condition: service_completed_successfully
    networks:
      - blood-donation-network

volumes:
  mongo_data:
    driver: local

networks:
  blood-donation-network:
    driver: bridge
